# Generated by Django 5.2.5 on 2025-09-01 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address to block from accessing the application",
                        unique=True,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for blocking this IP address",
                        max_length=255,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this IP was blocked",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this block is currently active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked IP",
                "verbose_name_plural": "Blocked IPs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address of the client making the request"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the request was made",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="URL path that was requested", max_length=255
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country of the client based on IP geolocation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City of the client based on IP geolocation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Region/State of the client based on IP geolocation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, help_text="Latitude coordinate", null=True
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, help_text="Longitude coordinate", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Log",
                "verbose_name_plural": "Request Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SuspiciousIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address flagged as suspicious"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Reason why this IP was flagged as suspicious",
                        max_length=255,
                    ),
                ),
                (
                    "flagged_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this IP was flagged",
                    ),
                ),
                (
                    "request_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of requests that triggered the flag",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Severity level of the suspicious activity",
                        max_length=20,
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this suspicious activity has been resolved",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suspicious IP",
                "verbose_name_plural": "Suspicious IPs",
                "ordering": ["-flagged_at"],
                "unique_together": {("ip_address", "reason", "flagged_at")},
            },
        ),
    ]
